import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "maplibre-gl/dist/maplibre-gl.css";
import "@geoman-io/maplibre-geoman-free/dist/maplibre-geoman.css";
import "./globals.css";
import { getThemeIds, getThemeStyleSheet } from "@/lib/theme-specs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeIds = getThemeIds();
const themeStyleSheet = getThemeStyleSheet();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const themeIds = ${JSON.stringify(themeIds)};
                  const theme = localStorage.getItem('ranchos-theme');
                  document.documentElement.classList.remove(...themeIds);
                  if (theme && themeIds.includes(theme)) {
                    document.documentElement.classList.add(theme);
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
        <style
          id="markdown-theme-styles"
          dangerouslySetInnerHTML={{
            __html: themeStyleSheet,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
